version: "3.7"

networks:
  main:
    name: main_network

volumes:
  dbdata:

services:
  services-php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - services-mysql
    networks:
      - main
    container_name: ns-crawler-services-php

  services-mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 33088:3306
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: sample
    networks:
      - main
    container_name: ns-crawler-services-mysql
